LOCAL_PATH := $(call my-dir)

# OPScreenRecord
include $(CLEAR_VARS)
LOCAL_MODULE := OPScreenRecord
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := OPScreenRecord.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_DEX_PREOPT := false
LOCAL_PRODUCT_MODULE := true
include $(BUILD_PREBUILT)